language: r
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo apt-get remove libgeos-c1 # conflicts with ppa
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

warnings_are_errors: true

r_packages:
  - sf
